---
env:
    es6: true
    node: true
    jest: true
parser: babel-eslint
extends:
    - "airbnb-base"
    - "prettier"
    - "plugin:react/recommended"
rules:
    quotes:
        - error
        - single
    import/no-dynamic-require:
        - off
    object-curly-spacing:
        - warn
    react/react-in-jsx-scope:
        - off
